version: '2'
services:
  web:
    build: .
    container_name: payment_web
    command: npm run start:dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3001:3000"

